
---
dist: bionic
language: minimal

cache:
  directories:
    - /home/travis/.vagrant.d/boxes

jobs:
  include:

    - stage: build
      install:
        - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
        - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
        - sudo dpkg -i vagrant_2.2.9_x86_64.deb
        - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload
      script:
        - travis_wait sudo vagrant up --provider=libvirt nodejs-ubuntu1804
        - travis_wait sudo vagrant ssh nodejs-ubuntu1804 -- sudo salt-call state.highstate
        - travis_wait sudo vagrant ssh nodejs-ubuntu1804 -- sudo salt-call state.sls sampleapps
        - travis_wait sudo vagrant ssh nodejs-ubuntu1804 -- "cd /opt/sampleapps/apps/math && npm install"
        - travis_wait sudo vagrant ssh nodejs-ubuntu1804 -- "cd /opt/sampleapps/apps/math && npm run dev"
        - travis_wait sudo vagrant ssh nodejs-ubuntu1804 -- "cd /opt/sampleapps/apps/zeromq-pushpull && npm install"
        - travis_wait sudo vagrant ssh nodejs-ubuntu1804 -- "cd /opt/sampleapps/apps/kafka-pubsub && npm install"
        - sudo vagrant destroy --force nodejs-ubuntu1804

    - stage: release
      install:
        - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh
        - sudo bash install.sh
        - nvm install lts/*
        - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          all_branches: true 

notifications:
  slack:
    secure: cdGmzfm8F+6tCX7ZRXTSZfTzSmKQlVH+CVaS0mQWECf6Qe/7Ftndqj14LIuGgbVURZrKQcl0RXN23bsZCTTbxFgNnLKMUpsryqPTplOfGUrnYZzJ03NbRJ/MxaqblTpNP/kensskGlVq+UQA0V9bBA0QTaNdVGD60SwyFrFPk3KmbeTjUdF5lY1bBjU+vXq0fXJs8TQh/eDnxHNZO5gw4w3VpB6boBVoudJnpz1znAP1C8+xBK6R7bH5+QHE6tl4ZEWrT/NgpJ8whS76A67LO522jq7F/7FzRHSL+cUi1qkhZRO3eFG8OuilebXJu2snGfd+Yb5U48xR29jVhfzpAmPi5LwJbqTHgNM4ic6GyLECc6F7ET9J0OeSwG2n9tL/H3YthS4uqz4Do7tKq3d0bNMIaIxnXYP3/zmh/+5XEOdIfuqOUGszIS6H47hgxFULi0Zj9nLpAn2FbA2YSnT7d0torQcJZxBfWUYIvjjfvrMDO4nHGKHpbbymYUP/um2+Iw1fpMWHsCRzaXW5T11IhKPwhT7ToEtaBh/RVgdd63rZOg2vZL4Ul+mLofsNKLD9rAdsVJKAgT7B61yWXmRI6c8az89g3VmyQqN8CYo5tZm8gOVZqZOtvjflbwpNqw3PmuX4qG5P8CvuG7ojcJq5pSflk1yBfoYQdBztEZLKn5I=
