apiVersion: v1
kind: Pod
metadata:
  name: kong-pod
spec:
  restartPolicy: Never
  containers:
  - name: kong
    image: docker.io/library/kong:2.1.4
    ports:
    - containerPort: 8000
      hostPort: 8000
      hostIP: 0.0.0.0
      protocol: tcp
    - containerPort: 8443
      hostPort: 8443
      hostIP: 0.0.0.0
      protocol: tcp
    - containerPort: 8001
      hostPort: 8001
      hostIP: 0.0.0.0
      protocol: tcp
    - containerPort: 8444
      hostPort: 8444
      hostIP: 0.0.0.0
      protocol: tcp
    volumeMounts:
    - mountPath: /etc/kong/kong.conf:ro,z
      name: kongconf
  volumes:
  - name: kongconf
    hostPath:
      path: /opt/sampleapps/apps/kong-podman/kong.conf
