apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  restartPolicy: Never
  containers:
  - name: postgres
    image: postgres:13.1-alpine
    command: ['postgres']
    ports:
    - containerPort: 5432
      protocol: tcp
    env:
    - name: PGDATA
      value: /var/lib/postgresql/data
    - name: POSTGRES_PASSWORD
      value: abcde12345
    volumeMounts:
    - mountPath: /docker-entrypoint-initdb.d/initdb.sql
      name: initdb
      readOnly: true
  volumes:
  - name: initdb
    hostPath:
      path: /opt/sampleapps/apps/kong-podman/initdb.sql
