apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
spec:
  restartPolicy: Never
  containers:
  - name: zookeeper
    image: docker.io/bitnami/zookeeper:3.6.2
    command: ['/opt/bitnami/scripts/zookeeper/run.sh']
    ports:
    - containerPort: 2181
      protocol: tcp
    env:
    - name: PATH
      value: /opt/bitnami/java/bin:/opt/bitnami/zookeeper/bin:/opt/bitnami/common/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: BITNAMI_APP_NAME
      value: zookeeper
    - name: ALLOW_ANONYMOUS_LOGIN
      value: yes
  - name: kafka
    image: docker.io/bitnami/kafka:2.6.0
    command: ['/opt/bitnami/scripts/kafka/run.sh']
    ports:
    - containerPort: 9092
      protocol: tcp
    env:
    - name: PATH
      value: /opt/bitnami/kafka/bin:/opt/bitnami/java/bin:/opt/bitnami/common/bin:/opt/bitnami/kafka/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: BITNAMI_APP_NAME
      value: kafka
    - name: KAFKA_BROKER_ID
      value: 1
    - name: KAFKA_CFG_ZOOKEEPER_CONNECT
      value: 127.0.0.1:2181
    - name: ALLOW_PLAINTEXT_LISTENER
      value: yes
    - name: KAFKA_LISTENERS
      value: PLAINTEXT://:9092
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka-pod:9092  # KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
