apiVersion: v1
kind: Pod
metadata:
  name: producer-pod
spec:
  restartPolicy: Never
  containers:
  - name: producer
    image: localhost/extra2000/prodcon:latest
    command: ['npm', 'run', 'producer']
    workingDir: /srv/project
