apiVersion: v1
kind: Pod
metadata:
  name: zeromq-pushpull-pod
spec:
  restartPolicy: Never
  containers:
  - name: producer
    image: localhost/extra2000/zeromq-pushpull
    command: ['npm', 'run', 'producer']
    workingDir: /srv/project
    ports:
    - containerPort: 3000
      hostPort: 3000
      protocol: tcp
  - name: worker
    image: localhost/extra2000/zeromq-pushpull
    command: ['npm', 'run', 'worker']
    workingDir: /srv/project
